config {
  type: "view",
  description: "This view contains the datatamart used for testing",
  columns: {
    AreaCode: "The identifier of a parking zone with city_code-number_with_0_padding, representing the specific parking area.",
    NTickets: "The number of tickets generated during the given hour, indicating parking demand.",
    TimeStart1H: "The datetime of the data, truncated to the start of each hour, used for temporal analysis.",
    Capacity: "The maximum number of parking slots that the area has, defining the potential supply.",
    CityCode: "The code identifying the city the zone belongs to, used for geographical segmentation.",
    AvailableSpots: "The number of available parking spots, computed as the maximum difference between Capacity and NTickets, ensuring a non-negative result.",
    Hour: "Extracted hour from TimeStart1H, used for hourly trend analysis.",
    WeekDay: "Extracted day of the week from TimeStart1H, indicating the weekday for further temporal segmentation.",
    is_mon: "Boolean flag indicating whether the record corresponds to a Monday, useful for modeling weekly patterns.",
    is_tue: "Boolean flag for Tuesday records.",
    is_wed: "Boolean flag for Wednesday records.",
    is_thu: "Boolean flag for Thursday records.",
    is_fri: "Boolean flag for Friday records.",
    is_sat: "Boolean flag for Saturday records.",
    is_sun: "Boolean flag for Sunday records.",
    Seconds: "UNIX timestamp of TimeStart1H, facilitating time series analysis.",
    AverageTicketsPastDay: "Average number of tickets in the past day, providing short-term demand trends.",
    AverageTicketsPastWeek: "Average tickets issued in the past week, offering insights into weekly demand fluctuations.",
    AverageTicketsPastMonth: "Monthly average of tickets, illustrating long-term demand patterns.",
    AverageTicketsPerHour: "Average number of tickets for each hour, across all days, highlighting hourly demand.",
    STDTicketsPerHour: "Standard deviation of tickets per hour, measuring hourly demand variability.",
    AverageTicketsPerDay: "Daily average ticket count, reflecting day-to-day demand trends.",
    STDTicketsPerDay: "Standard deviation of daily tickets, indicating variability in daily demand.",
    AverageTicketsPerDayHour: "Average ticket count per day and hour, providing detailed temporal demand insights.",
    STDTicketsPerDayHour: "Standard deviation of tickets per day and hour, assessing variability in detailed temporal demand.",
    MedTicketsPerDayHour: "Median of tickets per specific day and hour, offering a robust measure of central tendency for demand.",
    MedTicketsPerDay: "Median ticket count per day, reflecting central demand trends on a daily basis.",
    MedTicketsPerHour: "Median of tickets for each hour, highlighting central hourly demand trends."
  }
}

SELECT *
FROM ${ref("datamart")}
WHERE 
    TimeStart1H >= CAST(DATE_SUB(CURRENT_DATE(), INTERVAL ${constants.TESTING_START_MONTHS} MONTH) AS TIMESTAMP)